apiVersion: v1
kind: Service
metadata:
  name: claude-transcript-viewer-backend
  labels:
    app: claude-transcript-viewer-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: claude-transcript-viewer-backend
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
