apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
    tier: infrastructure
spec:
  type: ClusterIP
  selector:
    app: localstack
    tier: infrastructure
  ports:
    - name: edge
      protocol: TCP
      port: 4566
      targetPort: 4566
